alias grepc='grep -ihHnr --include=\*.{c,cpp,h}'
alias grepp='grep -ihHnr --include=\*.{py}'
alias grepy='grep -ihHnr --include=\*.{yml,yaml}'
alias aliv='cd /c/Users/allenma/Documents/projects/acculoadiv'
alias mate='cd /c/Users/allenma/Documents/projects/acculoadiv.AccuMate'
alias ml='cd /c/Users/allenma/Documents/projects/legacyproducts.microloadnet/source'
alias mfl='cd /c/Users/allenma/Documents/projects/legacyproducts.microflownet-liquid/source'
alias mfg='cd /c/Users/allenma/Documents/projects/legacyproducts.microflownet-gas/source'
alias al3='cd /c/Users/allenma/Documents/projects/legacyproducts.al3xnet/source'
alias scripts='cd /c/Users/allenma/Documents/projects/Internal-Software-Tools.automated_testing/python/modbus/accuload/tests'
alias LOCAL='cd /c/Users/allenma/AppData/Local'
alias AL3REM='./al3remotedisplay.exe COM0 ADDRC0A84C01 QUAD &'
alias AL3REM2='./al3remotedisplay.exe COM0 ADDRC0A8B54F QUAD &'
alias SOFT_AL3='./al3remotedisplay.exe COM0 ADDRC0A8B538 &'
alias github='cd /c/Users/allenma/Documents/Scripts_BASH_Repo'
alias gui='sudo cp /etc/default/grub.gui /etc/default/grub && sudo update-grub && reboot'
alias console='sudo cp /etc/default/grub.term /etc/default/grub && sudo update-grub && reboot'
alias transfer='cd ~/transfer'
alias zenva='cd /c/Users/allenma/Documents/zenva'
alias sketch=' cd /c/Users/allenma/Documents/arduino-1.8.13/portable/sketchbook'
alias lsr='ls -R'
alias craftos='cd /c/Users/allenma/AppData/Roaming/CraftOS-PC'
alias python='winpty python.exe'
alias t='$HOME/AppData/Local/Programs/Python/Python39/Scripts/todo.py'
alias home='cd ~/Documents/HOME'
alias metermate='cd /c/Users/allenma/Documents/projects/legacyproducts.metermate'
